dist: trusty
sudo: required

language: r
sudo: required
cache: packages

r:
  - release
  - devel

#warnings_are_errors: false
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get update -q

apt_packages:
  - libssl-dev
  - libcurl4-openssl-dev
  - netcdf-bin
  - libnetcdf-dev
  - gdal-bin
  - libgdal-dev
  - libudunits2-dev
  - libjq-dev
  - libv8-3.14-dev
  - libprotobuf-dev
  - protobuf-compiler

r_packages:
  - devtools
  - Rcpp
  - roxygen2
  - survival

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
